Tools=function(){function g(a,b,d,c){for(var k=0,e=[b],h=d.length,f=this,b=0;b<h;b++)this[d[b]]=function(b){return function(d){void 0===e[b]&&k++;e[b]=d;return k<h?f:a.apply(c,e)}}(b+1)}function b(a,b){var d,c;if(null==this)throw new TypeError(" this is null or not defined");var e=Object(this),h=e.length>>>0;if("[object Function]"!={}.toString.call(a))throw new TypeError(a+" is not a function");b&&(d=b);for(c=0;c<h;){var f;c in e&&(f=e[c],a.call(d,f,c,e));c++}}function a(a){if(null===this||void 0===
this)throw new TypeError("Object is null or undefined");var b=0,d=this.length>>0,c;if("function"!==typeof a)throw new TypeError("First argument is not callable");if(2>arguments.length){if(0===d)throw new TypeError("Array length is 0 and no second argument");c=this[0];b=1}else c=arguments[1];for(;b<d;)b in this&&(c=a.call(void 0,c,this[b],b,this)),++b;return c}function h(a,b){if(null==this)throw new TypeError;var d=Object(this),c=d.length>>>0;if("function"!=typeof a)throw new TypeError;for(var e=0;e<
c;e++)if(e in d&&!a.call(b,d[e],e,d))return!1;return!0}function e(a){if(null==this)throw new TypeError;var b=Object(this),d=b.length>>>0;if(0===d)return-1;var c=0;0<arguments.length&&(c=Number(arguments[1]),c!=c?c=0:0!=c&&Infinity!=c&&-Infinity!=c&&(c=(0<c||-1)*Math.floor(Math.abs(c))));if(c>=d)return-1;for(c=0<=c?c:Math.max(d-Math.abs(c),0);c<d;c++)if(c in b&&b[c]===a)return c;return-1}function f(a,b){a.each(function(a,b){return 0<$(b).outerWidth()})?b.call():window.setTimeout(function(){f(a,b)},
100)}return{spaceEvenly:function(a){var b=a.innerWidth(),d=a.children(),c=0;d.css({position:"absolute"}).each(function(a,e){var e=$(e),i=Math.floor(a<d.length-1?b/d.length:b-c);e.css({left:c+(0==a?0:-1),top:0});e.width(i);var h=e.outerWidth();e.width(2*i-h+1);c+=i})},$arr:function(a){return a.reduce(function(a,b){return a.add($(b))},$())},jqToString:function(a){return"id="+a.attr("id")+", class="+a.attr("class")},arrays:function(){Array.prototype.reduce||(Array.prototype.reduce=a);Array.prototype.forEach||
(Array.prototype.forEach=b);Array.prototype.every||(Array.prototype.every=h);Array.prototype.indexOf||(Array.prototype.indexOf=e)},prependForEach:function(a,b){return function(d){a.forEach(function(a){a[b](function(){var b=Array.prototype.slice.call(arguments);b.unshift(a);d.apply(this,b)})})}},bind:function(a,b){return function(){return a.apply(b,arguments)}},assertType:function(a,b){var d=eval(a);if(!(b instanceof d))throw a+" expected";},assertArrayOf:function(a,b){var d=eval(a);if(!(b instanceof
Array)||!b.every(function(a){return a instanceof d}))throw"Array of "+a+" expected";},uid:function(){var a=0;return function(){return a++}}(),log:function(){},mixin:function(a,e,d){b.call(d,function(b){b in a&&(e[b]=a[b])})},everyIn:function(a,b,d){var c=!0,e;for(e in a){var h=a[e];h instanceof b&&(c=c&&d(h))}return c},optionHash:function(a,b){for(var d in b)d in a||(a[d]=b[d]);return a},onLoad:f,defaultEventSubscription:function(a){var b=[];return{removeListener:function(a){a=b.indexOf(a);if(0>a)throw"No such listener";
b.splice(a,1)},addListener:function(d){d instanceof Function||a.forEach(function(a){if(!("notify"+a in d&&d["notify"+a]instanceof Function))throw"Listener "+d+" lacks event handling routine notify"+a;});b.push(d)},fire:function(d,c){if(0>a.indexOf(d))throw"No such event";b.forEach(function(a){if(a instanceof Function)a(d,c);else a["notify"+d](c)})}}},optionHashClone:function(a,b){var d={},c;for(c in a)d[c]=a[c];for(c in b)c in a||(d[c]=b[c]);return d},chainableFunction:function(a,b,d){return function(c){return new g(a,
c,b,d)}}}}();Tools.arrays();
var OverlayChapter=function(){function g(b,a){this.index=null;this.slides=b;this.length=b.length;this.options=a;this.forEachSlide=Tools.bind(this.slides.forEach,this.slides);Tools.mixin(a,this,["onLeave","onEnter"])}g.prototype={nextSlide:function(){},prevSlide:function(){},setIndex:function(b){this.index=b},getIndex:function(){return this.index},get:function(b){return this.slides[b]},getTitle:function(){return this.options.title},hasTitle:function(){return"title"in this.options},setTab:function(b){this.elem=
b},getTab:function(){return this.elem}};return g}(),OverlayController=function(){function g(b,a){b.forEach(function(a,b,f){a instanceof OverlaySlide&&(f[b]=new OverlayChapter([a],{}))});this.chapters=b;this.model=new OverlayModel(this,b);this.view=new OverlayView(this,a)}g.prototype={viewReady:function(){this.model.loaded()},nextSlide:function(){this.model.nextSlide()},prevSlide:function(){this.model.prevSlide()},firstSlide:function(){this.model.jumpSlide(0)},goToSlide:function(b){this.model.jumpSlide(b)},
lastSlide:function(){this.model.jumpSlide(this.model.length-1)},selectChapter:function(b){this.model.selectChapter(b)},toggleAnnotation:function(){this.model.toggleAnnotation()}};return g}(),OverlayModel=function(){function g(a,h){this.chapters=h;this.forEachChapter=Tools.bind(this.chapters.forEach,this.chapters);this.forEachSlide=Tools.prependForEach(this.chapters,"forEachSlide");this.currentSlide=0;this.annotationEnabled=!1;var e=0;this.chapters.forEach(function(a,b){a.setIndex(b);e+=a.length});
this.length=e;var f=0,g=this.slides=[],j=this.anyAnnotations=[],d=this.slidesPresent=[],c=this;this.forEachSlide(function(a,e){e.setGlobalIndex(f);e.setChapter(a);e.setModel(this);g[f]=e;d[f]=[];0<f&&(d[f]=c.slideSetOperation(b,f-1,f));d[f].push(e);j[f]=!1;d[f].forEach(function(a){j[f]|=a.hasAnnotation()});++f})}var b=!0;g.prototype={forEachPresentSlide:function(a){this.slidesPresent[this.currentSlide].forEach(a)},addListener:function(a){this.listeners=a},jumpSlide:function(a){this.currentSlide!=
a&&this.changeSlide("slideSelected",a)},nextSlide:function(){this.currentSlide<this.length-1&&this.changeSlide("nextSlide",this.currentSlide+1)},prevSlide:function(){0<this.currentSlide&&this.changeSlide("prevSlide",this.currentSlide-1)},selectChapter:function(a){if(0>a||a>this.chapters.length)throw new RangeError("slide index out of bounds");a=this.chapters[a].get(0).getGlobalIndex();this.currentSlide!==a&&this.changeSlide("slideSelected",a)},toggleAnnotation:function(){this.annotationEnabled=!this.annotationEnabled;
this.listeners.annotationToggle()},loaded:function(){this.notifyEnter({fro:null,froSlide:null,toSlide:this.get(),toChapter:this.get().getChapter(),chapterChanged:!0,enterList:this.slidesPresent[0],leaveList:[]})},changeSlide:function(a,b){var e=this.get(),f=this.currentSlide,g=this.get(b),e={fro:f,froSlide:e,toSlide:g,froChapter:e.getChapter(),toChapter:g.getChapter(),chapterChanged:!g.sameChapter(e),enterList:this.slideSetOperation(!1,b,f),leaveList:this.slideSetOperation(!1,f,b)};this.notifyLeave(e);
this.listeners[a](b);this.currentSlide=b;this.notifyEnter(e)},slideSetOperation:function(a,b,e){var f=[];this.slidesPresent[b].forEach(function(b){b.presentAt(e)==a&&f.push(b)});return f},notifyLeave:function(a){var b=this.listeners;a.leaveList.forEach(function(b){if("onLeave"in b)b.onLeave(a.toSlide)});if(a.chapterChanged&&"onLeave"in a.froChapter)a.froChapter.onLeave(a.toChapter);a.leaveList.forEach(function(e){b.slideLeft(e,a.toSlide)});a.chapterChanged&&b.chapterLeft(a.froChapter,a.toChapter)},
notifyEnter:function(a){var b=this.listeners;null!==a.froSlide&&(a.chapterChanged&&b.chapterEntered(a.froChapter,a.toChapter),a.enterList.forEach(function(e){b.slideEntered(a.froSlide,e)}));if(a.chapterChanged&&"onEnter"in a.toChapter)a.toChapter.onEnter(a.froChapter);a.enterList.forEach(function(b){if("onEnter"in b)b.onEnter(a.froSlide)})},get:function(){return this.slides[0<arguments.length?arguments[0]:this.currentSlide]},getChapter:function(){return this.get().getChapter()}};return g}(),OverlaySlide=
function(){function g(a){this.fadeInDuration=b;this.slideSpan=1;this.text="";Tools.mixin(a,this,"problemText,element,annotation,slideSpan,onEnter,onLeave,text,fadeIn,fadeInDuration".split(","))}var b=1E3;g.prototype={setGlobalIndex:function(a){this.globalIndex=a},getGlobalIndex:function(){return this.globalIndex},presentAt:function(a){return a>=this.globalIndex&&a<this.globalIndex+this.slideSpan},doesFadeIn:function(){return this.fadeIn},getFadeInDuration:function(){return this.fadeInDuration},setChapter:function(a){this.chapter=
a},getChapter:function(){return this.chapter},sameChapter:function(a){return this.getChapter()==a.getChapter()},setModel:function(a){this.model=a},getElement:function(){if(this.hasElement())return this.element;throw"Is not a div slide";},hasElement:function(){return"element"in this},hasAnnotation:function(){return"annotation"in this},getAnnotation:function(){return this.annotation},nextSlide:function(){},getText:function(){return this.text},getProblemText:function(){return this.problemText},hasText:function(){return""!=
this.text},hasProblemText:function(){return""!=this.problemText},prevSlide:function(){},play:function(){this.model.listeners.play(this)}};return g}(),OverlayView=function(){function g(b,a){this.controller=b;this.model=b.model;this.model.addListener(this);Tools.optionHash(a,{tabContainer:$(),textContainer:$(),problemTextContainer:$(),buttonJumpToFirstSlide:$(),buttonJumpToLastSlide:$(),buttonButtonNextSlide:$(),buttonPrevSlide:$(),buttonToggleAnnotation:$(),slidenumber:$(),activeTabClass:"chapter-active",
tabClass:"ov-chapter"});this.options=a;this.originalTextContents=this.options.textContainer.html();this.renderTabs();this.renderSlideNumber(this.model.get());this.renderSlideText(this.model.get());this.renderSlideProblem(this.model.get());this.renderSlides();this.renderControls();this.controller.viewReady()}g.prototype={nextSlide:function(){},prevSlide:function(){},slideSelected:function(){},chapterLeft:function(b){this.renderTabHide(b)},chapterEntered:function(b,a){this.renderTabShow(a)},annotationToggle:function(){this.model.annotationEnabled?
this.showAnnotations():this.hideAnnotations()},showAnnotations:function(){this.options.buttonToggleAnnotation.addClass("active");this.model.forEachPresentSlide(function(b){b.hasAnnotation()&&b.getAnnotation().show()})},hideAnnotations:function(){this.options.buttonToggleAnnotation.removeClass("active");this.model.forEachPresentSlide(function(b){b.hasAnnotation()&&b.getAnnotation().hide()})},slideLeft:function(b,a){b.hasAnnotation()&&this.renderAnnotationHide(b);b.hasElement()&&(a.doesFadeIn()&&a.getGlobalIndex()==
b.getGlobalIndex()+1?this.fadeOut(b,a.getFadeInDuration()):this.renderSlideHide(b));Tools.log("Left "+b.getGlobalIndex());this.renderSlideText(a);this.renderSlideProblem(a);this.renderSlideNumber(a);this.model.anyAnnotations[a.getGlobalIndex()]||this.options.buttonToggleAnnotation.hide()},slideEntered:function(b,a){a.hasAnnotation()&&this.model.annotationEnabled&&this.renderAnnotationShow(a);a.hasElement()&&(a.doesFadeIn()&&a.getGlobalIndex()==b.getGlobalIndex()+1?this.fadeIn(a,a.getFadeInDuration()):
this.renderSlideShow(a));this.renderSlideText(a);this.renderSlideProblem(a);this.renderSlideNumber(a);Tools.log("Entered "+a.getGlobalIndex());this.model.anyAnnotations[a.getGlobalIndex()]&&this.options.buttonToggleAnnotation.show()},play:function(){},stopRewind:function(){},renderTabs:function(){var b=this.options.tabContainer,a=this;this.model.forEachChapter(function(g){if(g.hasTitle()){var e=$('<div class="'+a.options.tabClass+'"><a>'+g.getTitle()+"</a></div>");e.click(function(){a.controller.selectChapter(g.getIndex())});
b.append(e);g.setTab(e)}});Tools.spaceEvenly(b);this.renderTabShow(this.model.getChapter())},renderTabShow:function(b){b.hasTitle()&&b.getTab().addClass(this.options.activeTabClass)},renderTabHide:function(b){b.hasTitle()&&b.getTab().removeClass(this.options.activeTabClass)},renderSlideNumber:function(b){this.options.slidenumber.html(b.getGlobalIndex()+1+"/"+this.model.length)},renderSlides:function(){this.model.forEachSlide(function(b,a){a.hasElement()&&a.getElement().hide()});this.model.get().hasElement()&&
this.renderSlideShow(this.model.get())},renderAnnotationHide:function(b){b.getAnnotation().hide()},renderAnnotationShow:function(b){b.getAnnotation().show()},renderSlideHide:function(b){b.getElement().stop(!0,!0).hide()},renderSlideShow:function(b){b.getElement().stop(!0,!0).show()},fadeOut:function(b,a){b.getElement().stop(!0,!0).delay(a).hide(-1)},fadeIn:function(b,a){b.getElement().stop(!0,!0).fadeIn(a)},renderSlideText:function(b){klett.Console.changeContainer(this.options.textContainer,b.hasText()?
b.getText():this.originalTextContents)},renderSlideProblem:function(b){b.hasProblemText()&&klett.Console.changeContainer(this.options.problemTextContainer,b.getProblemText())},renderControls:function(){this.options.buttonJumpToFirstSlide.click(Tools.bind(this.controller.firstSlide,this.controller));this.options.buttonJumpToLastSlide.click(Tools.bind(this.controller.lastSlide,this.controller));this.options.buttonButtonNextSlide.click(Tools.bind(this.controller.nextSlide,this.controller));this.options.buttonPrevSlide.click(Tools.bind(this.controller.prevSlide,
this.controller));this.options.buttonToggleAnnotation.click(Tools.bind(this.controller.toggleAnnotation,this.controller));this.model.anyAnnotations[0]?this.options.buttonToggleAnnotation.show():this.options.buttonToggleAnnotation.hide()}};return g}();
